# Generated by Django 3.1.3 on 2020-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='number_views',
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
